### ISSUE TITLE
Backstage not appearing - "i.init is not a function"

### ISSUE THREAD

**Issue by DawnPaladin** [klembot/chapbook#101]
**Describe the bug**
Hello! I've downloaded a fresh copy of Twine onto my Macbook. When I create a new story, set the format to Chapbook, and click "Test", a red error briefly flashes on the screen before the story's text is displayed. When I open the developer tools, the error reads "Uncaught TypeError: i.init is not a function". 

**To Reproduce**
Download Twine 2.3.12 and install on OSX. Create a new story. Change story format to "Chapbook 1.2.1". Click "Test".

**Expected behavior**
Error-free story

**Stories and screenshots**
Error doesn't appear when I click "View Proofing Copy" or "Publish to File", only when I click  "Test". HTML produced is in [this gist](https://gist.github.com/DawnPaladin/9378f6eae657b52aba2de32743db187a).
<img width="764" alt="image" src="https://user-images.githubusercontent.com/5524469/108615527-b314b980-73ca-11eb-903a-e677f9f789c7.png">

**Environment**
MacOS on M1 Macbook Pro. Firefox 85.0.2 and Chrome 88.0.4324.182.

**Additional context**
I checked Harlowe, Snowman, and SugarCube and I'm not seeing the error there.

**Comment by DawnPaladin** [comment]
Update: Perusing the Chapbook guide tells me I'm supposed to be seeing a "Backstage" view when I click Test. I am not seeing that. That may be a more immediate problem. Editing the issue title to reflect this.

**Comment by ryomams** [comment]
Try updating Twine to 2.1.13, it seems that a relevant fix has been published. This doesn't appear to be a Chapbook issue, so much as a Twine issue.

Source: [https://www.patreon.com/posts/47595312](https://www.patreon.com/posts/47595312)

**Comment by DawnPaladin** [comment]
Yep, the update fixed it. Thank you! 🙇‍♂️
