### ISSUE TITLE
I Can't Add Chapbook to Twine-js

### ISSUE THREAD

**Issue by everythingability** [klembot/chapbook#17]
Hello,

I discovered Chapbook and think it is beautiful in many ways.

For a student project I would like to use Chapbook with Twine-js. I can get Twine-js running, but it doesn't let me add new Story formats to it. If I add it, under-the-hood, it doesn't recognise it as a story format.

Can chapbook be provided as a folder that can be dropped into Twine-js? Like this...

Chapbook-1.0.0
   format.js
   icon.svg
   LICENCE 

...at the moment, somewhere in the repo there is just a format.js file.

Thanks.

**Comment by ChapelR** [comment]
You add a new format to Twine 2 via an option on the story list, using the URL provided on chapbook's website. Not by adding it to Twine's internal file structure.

**Comment by everythingability** [comment]
The interface to do that (add a new format) doesn't work or isn't visible in the Twine-js version... which although I now can get npm to install and run, then errors so can't prove this to you... which is why I started trying to slide a Story format under the wire.

**Comment by greyelf** [comment]
@everythingability 
> The interface to do that (add a new format) doesn't work or isn't visible in the Twine-js version..

Could you indicate which of the following steps isn't working/visible for you:
- Selecting the **Format** option of the **Story List** screen to open the Installed Formats dialog.
- Selecting the **Add a New Format** tab to display the new format URL text field and button.
- Entering the URL of the Chapbook story format into the text field.
- Selecting the **+Add** button to install the referenced story format.

**Comment by everythingability** [comment]
It's like this...
https://www.youtube.com/watch?v=Mt_ND9YpEqU

**Comment by everythingability** [comment]
But the thing is/was that I *thought* stupidly that by running on a server, the Twine project created would be a collaborative one, in which everyone access it might create Passages, but it doesn't work like that does it... like a regular wiki.... Dur...

So my need for Twine-js is less pressing, I will use Desktop Twine. Thanks for your help though.

**Comment by ChapelR** [comment]
Twine-js is desktop Twine. Twine-js is just the source code for the Twine 2 app, both the downloaded and hosted version.

**Comment by everythingability** [comment]
I am an idiot. Thank you for your help and kindness. There still is a bug though regarding the tab to add a format not showing.
