### ISSUE TITLE
'setup is not defined' when load google adsense js in chapbook

### ISSUE THREAD

**Issue by bobdos** [klembot/chapbook#31]
**Describe the bug**
'setup is not defined' when load google adsense js in chapbook

**To Reproduce**
* usually the google adsense js code is like this, for user to embed into html directly
```html
<script data-ad-client="ca-pub-xxx" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
```

* reference code is from here: ["Importing External JavaScript": Chapbook (v1.0.0)](https://twinery.org/cookbook/importexternaljs/chapbook/chapbook_importexternaljs.html)
* add pre-load script, especially the line of "newScript.data-ad-client = 'ca-pub-xxx';"
```javascript
// The following code is used from MDN for
// dynamically importing scripts
// https://developer.mozilla.org/en-US/docs/Web/API/HTMLScriptElement#Dynamically_importing_scripts

window.setup = {};

setup.loadError = function(oError) {
  throw new URIError("The script " + oError.target.src + " didn't load correctly.");
};

setup.loadScript = function(url, onloadFunction) {
  var newScript = document.createElement("script");
  newScript.onerror = setup.loadError;
  if (onloadFunction) { newScript.onload = onloadFunction; }
  document.head.appendChild(newScript);
	newScript.async = true;
        newScript.src = url;
	newScript.data-ad-client = 'ca-pub-xxx';
};
``` 
* then load adsesne js in chapter
```javascript
[JavaScript]
setup.loadScript("https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js", function(){});
```

**Expected behavior**
google adsense should be loaded successfully

**Stories and screenshots**

![image](https://user-images.githubusercontent.com/195643/77142363-f9cfa480-6ad3-11ea-896a-85bef0f140f4.png)

![image](https://user-images.githubusercontent.com/195643/77141946-b6286b00-6ad2-11ea-8f4c-65d4d804d618.png)

**Environment**
Mac OS 10.14.6
Browser Chrome 80.0.3987.132 (64bit)

**Additional context**

**Comment by greyelf** [comment]
@bobdos
The error you are reporting is not actually a result of a bug in the story format, the issue starts with an error in the code of your loadScript function. If you look at your web-browser's Console you will likely see the following error...

> Uncaught SyntaxError: Invalid left-hand side in assignment

...which is caused by the following line in your code...
```
newScript.data-ad-client = 'ca-pub-xxx';
```
Changing that line to the following will resolve that specific error...
```
newScript.setAttribute('data-ad-client', 'ca-pub-xxx');
```
...however that change won't fix the next problem of the specific JS file not loading.

**Comment by bobdos** [comment]
@greyelf cool, it's fixing my issue.

Thanks.
