### ISSUE TITLE
Consecutive lengthy pages causes new page to load at bottom of page instead of top

### ISSUE THREAD

**Issue by garlicrainbow** [klembot/chapbook#54]
**Describe the bug**
If two consecutive lengthy pages of text are linked from one to another by a fork at the bottom, the second page loads at the bottom of the page instead of the top.

**To Reproduce**
Create 2 consecutive pages of lengthy text, longer than the height of your browser, such that scrolling is required. Put a fork at the bottom of the first page that points to the second page. Play the story and click the fork. 

**Expected behavior**
I expect each page to load at the top, thus preventing spoilers and ensuring no text gets missed by the reader. 

**Environment**
Windows 10. Firefox 75. Twine 2.3.8. Chapbook 1.1

**Comment by mbaltus** [comment]
As a workaround, I put this at the top of each page, right below the vars section:
```
[JavaScript]
    window.scrollTo(0, 0);
```

**Comment by garlicrainbow** [comment]
Thanks for the suggestion! Trying that, I get an error message "An unexpected error has occurred". Am I missing something obvious? I don't know much about javascript.

**Comment by mbaltus** [comment]
I forgot to add the [cont] that has to be put after the javascript to resume the normal text. That should help!

**Comment by garlicrainbow** [comment]
That worked! Thanks a bunch :)
