### ISSUE TITLE
Issue with random numbers

### ISSUE THREAD

**Issue by Astrolingus** [klembot/chapbook#61]
**Describe the bug**
Using lookup variables of the random object is causing issues

**To Reproduce**
//This code:

rnum: random.d4 
--

ABC

//Produces the following error:
//An unexpected error has occurred.

//Uncaught TypeError: Cannot read property 'd4' of undefined"

//Similarly, this code produces an error

[if random.coinFlip]
Heads!

[else]
Tails!

//This code does not:

{random.d4}

**Expected behavior**

**Stories and screenshots**
If at all possible, please attach a story file demonstrating the problem. If applicable, add screenshots to help explain your problem.

**Environment**
I'm using a PC with Windows, and testing on a google chrome browser

**Additional context**

**Comment by ChapelR** [comment]
Are you on version 1.1.0 or 1.1.1. This should be fixed in 1.1.1 and higher afaik.

**Comment by Astrolingus** [comment]
Ah thanks!

I didn’t realize Twine default was to the earlier version!

Works great now, and sorry to bother you with this!

**Comment by everythingability** [comment]
Ah thank you fixed it.

p.s  Also the CSS example wasn't working... think the CSS itself was wrong... and needed a p :-) This works though....

[CSS]
#page article p{
    color:red;
    background-color: yellow;
    font-size: 2em;
    text-align: center;
    text-transform: uppercase;
    font-weight: bold;
    
    
}
#page{
    
   background-color: yellow; 
}
article{
    border:0px;
    
}

[continued]

This text should be in red.

Why isn't it?
