### ISSUE TITLE
I don't think random works.

### ISSUE THREAD

**Issue by everythingability** [klembot/chapbook#65]
At the top of my page I have

`chosen:random.d6

--

# You rolled a {chosen}

[if chosen === 1]
One.

[if chosen === 2]
Two.

[if chosen === 3]
Three.

[if chosen === 4]
Four.

[if chosen === 5]
Five.

[if chosen === 6]
Six.`

I get...

`An unexpected error has occurred.

Uncaught TypeError: Cannot read property 'd6' of undefined

Stack trace:
TypeError: Cannot read property 'd6' of undefined
    at Object.eval [as value] (eval at  (file:///private/var/folders/h5/m5x7b1x90b5801n_20mqcf540000gn/T/5f103c67-0401-4eb0-bc4d-d61651064e53.html:57:31787), :3:16)`

**Comment by ChapelR** [comment]
Sounds like you're using 1.1.0, see #61
