### ISSUE TITLE
Array/variables are not updated with player input

### ISSUE THREAD

**Issue by thistlesylph** [klembot/chapbook#81]
Interacting with dropdown menus, cycling links, or text input does not create or update variables. Creating the variable in the same passage as the dropdown menu in order to have a preselected choice lets Chapbook pull that variable in later passages, but if a player chooses a different value it still doesn't change to that value. 

This is my first bug report, please let me know if I need to add more info. :)

[Cat creator.zip](https://github.com/klembot/chapbook/files/4973252/Cat.creator.zip)

**Comment by greyelf** [comment]
There is a syntax error in each of your [{dropdown} menu](https://klembot.github.io/chapbook/guide/player-input/dropdown-menus-cycling-links.html) inputs, they are all missing a colon after the **for** keyword.

eg. Your code looks like...
```
{dropdown menu for 'statBody', choices: ['Chonky', 'Slinky']}
```

...when it should be...
```
{dropdown menu for: 'statBody', choices: ['Chonky', 'Slinky']}
```

**Comment by thistlesylph** [comment]
Ahh, thank you! I feel silly for missing this so many times.
